spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        encrypt:false
        composite:
        -
          type: git
          uri: https://github.com/sheekaat/peer-shared-config.git
        -
          type: git
          uri: https://github.com/sheekaat/{application}-{profile}.git
          
       